# TCL File Generated by Component Editor 14.1
# Thu May 07 19:15:39 BRT 2015
# DO NOT MODIFY


# 
# new_component "new_component" v1.0
#  2015.05.07.19:15:39
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module new_component
# 
set_module_property DESCRIPTION ""
set_module_property NAME new_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME new_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SpaceCraft
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SpaceCraft.vhd VHDL PATH SpaceCraft.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk50 clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address address Output 32
add_interface_port avalon_master chipselect chipselect Output 1
add_interface_port avalon_master readD read Output 1
add_interface_port avalon_master readdata readdata Input 16
add_interface_port avalon_master writeD write Output 1
add_interface_port avalon_master writedata writedata Output 16
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master readdatavalid readdatavalid Input 1
add_interface_port avalon_master transferrequest lock Output 1


# 
# connection point VGA
# 
add_interface VGA conduit end
set_interface_property VGA associatedClock clk25
set_interface_property VGA associatedReset reset
set_interface_property VGA ENABLED true
set_interface_property VGA EXPORT_OF ""
set_interface_property VGA PORT_NAME_MAP ""
set_interface_property VGA CMSIS_SVD_VARIABLES ""
set_interface_property VGA SVD_ADDRESS_GROUP ""

add_interface_port VGA VGA_R r Output 8
add_interface_port VGA VGA_G g Output 8
add_interface_port VGA VGA_B b Output 8
add_interface_port VGA VGA_HS hs Output 1
add_interface_port VGA VGA_VS vs Output 1
add_interface_port VGA VGA_SYNC_n sync Output 1
add_interface_port VGA VGA_CLK vga_clk Output 1
add_interface_port VGA VGA_BLANK_n blank Output 1


# 
# connection point TEST
# 
add_interface TEST conduit end
set_interface_property TEST associatedClock clock
set_interface_property TEST associatedReset reset
set_interface_property TEST ENABLED true
set_interface_property TEST EXPORT_OF ""
set_interface_property TEST PORT_NAME_MAP ""
set_interface_property TEST CMSIS_SVD_VARIABLES ""
set_interface_property TEST SVD_ADDRESS_GROUP ""

add_interface_port TEST sw sw Input 4


# 
# connection point clk25
# 
add_interface clk25 clock end
set_interface_property clk25 clockRate 0
set_interface_property clk25 ENABLED true
set_interface_property clk25 EXPORT_OF ""
set_interface_property clk25 PORT_NAME_MAP ""
set_interface_property clk25 CMSIS_SVD_VARIABLES ""
set_interface_property clk25 SVD_ADDRESS_GROUP ""

add_interface_port clk25 clk25 clk Input 1


# 
# connection point clk100
# 
add_interface clk100 clock end
set_interface_property clk100 clockRate 0
set_interface_property clk100 ENABLED true
set_interface_property clk100 EXPORT_OF ""
set_interface_property clk100 PORT_NAME_MAP ""
set_interface_property clk100 CMSIS_SVD_VARIABLES ""
set_interface_property clk100 SVD_ADDRESS_GROUP ""

add_interface_port clk100 clk100 clk Input 1


# 
# connection point LED
# 
add_interface LED conduit end
set_interface_property LED associatedClock clk100
set_interface_property LED associatedReset ""
set_interface_property LED ENABLED true
set_interface_property LED EXPORT_OF ""
set_interface_property LED PORT_NAME_MAP ""
set_interface_property LED CMSIS_SVD_VARIABLES ""
set_interface_property LED SVD_ADDRESS_GROUP ""

add_interface_port LED led led Output 4

