	Instrument_Unit u0 (
		.booster_mem_a            (<connected-to-booster_mem_a>),            // booster.mem_a
		.booster_mem_ba           (<connected-to-booster_mem_ba>),           //        .mem_ba
		.booster_mem_ck           (<connected-to-booster_mem_ck>),           //        .mem_ck
		.booster_mem_ck_n         (<connected-to-booster_mem_ck_n>),         //        .mem_ck_n
		.booster_mem_cke          (<connected-to-booster_mem_cke>),          //        .mem_cke
		.booster_mem_cs_n         (<connected-to-booster_mem_cs_n>),         //        .mem_cs_n
		.booster_mem_dm           (<connected-to-booster_mem_dm>),           //        .mem_dm
		.booster_mem_ras_n        (<connected-to-booster_mem_ras_n>),        //        .mem_ras_n
		.booster_mem_cas_n        (<connected-to-booster_mem_cas_n>),        //        .mem_cas_n
		.booster_mem_we_n         (<connected-to-booster_mem_we_n>),         //        .mem_we_n
		.booster_mem_reset_n      (<connected-to-booster_mem_reset_n>),      //        .mem_reset_n
		.booster_mem_dq           (<connected-to-booster_mem_dq>),           //        .mem_dq
		.booster_mem_dqs          (<connected-to-booster_mem_dqs>),          //        .mem_dqs
		.booster_mem_dqs_n        (<connected-to-booster_mem_dqs_n>),        //        .mem_dqs_n
		.booster_mem_odt          (<connected-to-booster_mem_odt>),          //        .mem_odt
		.clk_clk                  (<connected-to-clk_clk>),                  //     clk.clk
		.memory_mem_a             (<connected-to-memory_mem_a>),             //  memory.mem_a
		.memory_mem_ba            (<connected-to-memory_mem_ba>),            //        .mem_ba
		.memory_mem_ck            (<connected-to-memory_mem_ck>),            //        .mem_ck
		.memory_mem_ck_n          (<connected-to-memory_mem_ck_n>),          //        .mem_ck_n
		.memory_mem_cke           (<connected-to-memory_mem_cke>),           //        .mem_cke
		.memory_mem_cs_n          (<connected-to-memory_mem_cs_n>),          //        .mem_cs_n
		.memory_mem_ras_n         (<connected-to-memory_mem_ras_n>),         //        .mem_ras_n
		.memory_mem_cas_n         (<connected-to-memory_mem_cas_n>),         //        .mem_cas_n
		.memory_mem_we_n          (<connected-to-memory_mem_we_n>),          //        .mem_we_n
		.memory_mem_reset_n       (<connected-to-memory_mem_reset_n>),       //        .mem_reset_n
		.memory_mem_dq            (<connected-to-memory_mem_dq>),            //        .mem_dq
		.memory_mem_dqs           (<connected-to-memory_mem_dqs>),           //        .mem_dqs
		.memory_mem_dqs_n         (<connected-to-memory_mem_dqs_n>),         //        .mem_dqs_n
		.memory_mem_odt           (<connected-to-memory_mem_odt>),           //        .mem_odt
		.memory_mem_dm            (<connected-to-memory_mem_dm>),            //        .mem_dm
		.memory_oct_rzqin         (<connected-to-memory_oct_rzqin>),         //        .oct_rzqin
		.oct_rzqin                (<connected-to-oct_rzqin>),                //     oct.rzqin
		.reset_reset_n            (<connected-to-reset_reset_n>),            //   reset.reset_n
		.status_local_init_done   (<connected-to-status_local_init_done>),   //  status.local_init_done
		.status_local_cal_success (<connected-to-status_local_cal_success>), //        .local_cal_success
		.status_local_cal_fail    (<connected-to-status_local_cal_fail>),    //        .local_cal_fail
		.vga_r                    (<connected-to-vga_r>),                    //     vga.r
		.vga_g                    (<connected-to-vga_g>),                    //        .g
		.vga_b                    (<connected-to-vga_b>),                    //        .b
		.vga_hs                   (<connected-to-vga_hs>),                   //        .hs
		.vga_vs                   (<connected-to-vga_vs>),                   //        .vs
		.vga_sync                 (<connected-to-vga_sync>),                 //        .sync
		.vga_vga_clk              (<connected-to-vga_vga_clk>),              //        .vga_clk
		.vga_blank                (<connected-to-vga_blank>)                 //        .blank
	);

